"""AWS region and edge location data models."""

REGIONS = {
    "us-east-1": {
        "code": "us-east-1",
        "name": "US East (N. Virginia)",
        "city": "Virginia",
        "latitude": 39.0438,
        "longitude": -77.4874,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "us-west-2": {
        "code": "us-west-2",
        "name": "US West (Oregon)",
        "city": "Oregon",
        "latitude": 45.5945,
        "longitude": -122.1562,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "eu-west-1": {
        "code": "eu-west-1",
        "name": "Europe (Ireland)",
        "city": "Dublin",
        "latitude": 53.3498,
        "longitude": -6.2603,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "eu-central-1": {
        "code": "eu-central-1",
        "name": "Europe (Frankfurt)",
        "city": "Frankfurt",
        "latitude": 50.1109,
        "longitude": 8.6821,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "ap-southeast-1": {
        "code": "ap-southeast-1",
        "name": "Asia Pacific (Singapore)",
        "city": "Singapore",
        "latitude": 1.3521,
        "longitude": 103.8198,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "ap-northeast-1": {
        "code": "ap-northeast-1",
        "name": "Asia Pacific (Tokyo)",
        "city": "Tokyo",
        "latitude": 35.6762,
        "longitude": 139.6503,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "sa-east-1": {
        "code": "sa-east-1",
        "name": "South America (São Paulo)",
        "city": "São Paulo",
        "latitude": -23.5505,
        "longitude": -46.6333,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "af-south-1": {
        "code": "af-south-1",
        "name": "Africa (Cape Town)",
        "city": "Cape Town",
        "latitude": -33.9249,
        "longitude": 18.4241,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "ap-south-1": {
        "code": "ap-south-1",
        "name": "Asia Pacific (Mumbai)",
        "city": "Mumbai",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
    "me-south-1": {
        "code": "me-south-1",
        "name": "Middle East (Bahrain)",
        "city": "Bahrain",
        "latitude": 26.0667,
        "longitude": 50.5577,
        "status": "healthy",
        "current_load": 0.0,
        "request_count": 0,
        "avg_latency_ms": 0.0,
    },
}

EDGE_LOCATIONS = [
    {"code": "edge-nyc", "city": "New York", "latitude": 40.7128, "longitude": -74.0060},
    {"code": "edge-lax", "city": "Los Angeles", "latitude": 34.0522, "longitude": -118.2437},
    {"code": "edge-chi", "city": "Chicago", "latitude": 41.8781, "longitude": -87.6298},
    {"code": "edge-mia", "city": "Miami", "latitude": 25.7617, "longitude": -80.1918},
    {"code": "edge-lon", "city": "London", "latitude": 51.5074, "longitude": -0.1278},
    {"code": "edge-par", "city": "Paris", "latitude": 48.8566, "longitude": 2.3522},
    {"code": "edge-fra", "city": "Frankfurt", "latitude": 50.1109, "longitude": 8.6821},
    {"code": "edge-ams", "city": "Amsterdam", "latitude": 52.3676, "longitude": 4.9041},
    {"code": "edge-sin", "city": "Singapore", "latitude": 1.3521, "longitude": 103.8198},
    {"code": "edge-tyo", "city": "Tokyo", "latitude": 35.6762, "longitude": 139.6503},
    {"code": "edge-syd", "city": "Sydney", "latitude": -33.8688, "longitude": 151.2093},
    {"code": "edge-hkg", "city": "Hong Kong", "latitude": 22.3193, "longitude": 114.1694},
    {"code": "edge-bom", "city": "Mumbai", "latitude": 19.0760, "longitude": 72.8777},
    {"code": "edge-del", "city": "New Delhi", "latitude": 28.6139, "longitude": 77.2090},
    {"code": "edge-gru", "city": "São Paulo", "latitude": -23.5505, "longitude": -46.6333},
    {"code": "edge-jnb", "city": "Johannesburg", "latitude": -26.2041, "longitude": 28.0473},
    {"code": "edge-dxb", "city": "Dubai", "latitude": 25.2048, "longitude": 55.2708},
    {"code": "edge-icn", "city": "Seoul", "latitude": 37.5665, "longitude": 126.9780},
    {"code": "edge-osa", "city": "Osaka", "latitude": 34.6937, "longitude": 135.5023},
    {"code": "edge-yto", "city": "Toronto", "latitude": 43.6532, "longitude": -79.3832},
    {"code": "edge-ber", "city": "Berlin", "latitude": 52.5200, "longitude": 13.4050},
    {"code": "edge-mad", "city": "Madrid", "latitude": 40.4168, "longitude": -3.7038},
    {"code": "edge-mil", "city": "Milan", "latitude": 45.4642, "longitude": 9.1900},
]
