apiVersion: v1
kind: Service
metadata:
  name: routing-sim-backend
  labels:
    app: routing-sim
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: routing-sim
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: routing-sim-frontend
  labels:
    app: routing-sim
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: routing-sim
    component: frontend
